# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: My-Fantastic-Load-Pipeline

on:
  push:
    branches: [ master ]

jobs:
  build_and_load:

    name: build Node.js application
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [12.x]

    services:
      mydummyservice:
       image: docker://eszhlznkv/dummyload:firsttry
       ports: 
        - 49160:8080
    
    container: 
      image: docker://loadimpact/k6:latest
      ports: 
        - 49160:49160
    
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Local k6 test
      run: k6 run script.js
      
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v1
#       with:
#         node-version: ${{ matrix.node-version }}
#     - run: npm ci
#     - run: npm run build --if-present
      
#     - run: node server.js &
#     - run: echo "Application has been deployed!"
#     - run: curl http://localhost:49160/
   
#     - name: Checkout for nodeserver
#       uses: actions/checkout@v1
      
#     - name: run nodeserver in Docker 
#       uses: docker://eszhlznkv/dummyload:firsttry
#       with:
#         args: |
#            node server.js &
#         ports: 
#          49160:8080      

#     - name: Checkout for loadtest
#       uses: actions/checkout@v1
      
#     - name: k6 local test run 
#       uses: docker://loadimpact/k6:latest
#       with:
#        args: |
#           run script.js 
      

#   k6_loadtest_local:
    
#     name: k6 local test run 
#     runs-on: ubuntu-latest
#     container: docker://loadimpact/k6:latest
#     ports:
#     -  49160:49160

# # #     needs: [build]
  
#     steps:
#     - name: Checkout
#       uses: actions/checkout@v1
    
      
#     - name: Local k6 test
#       run: k6 run script.js
