# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: My-Fantastic-Load-Pipeline

on:
  push:
    branches: [ master ]

jobs:
  build:

    name: build Node.js application
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
#         node-version: [10.x, 12.x]
        node-version: [12.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: echo "Application has been deployed!"
    
#     - run: echo "Now we start load testing..."
    - name: Checkout for loadtest
      uses: actions/checkout@v1
      
    - name: k6 local test run 
      uses: docker://loadimpact/k6:latest
      with:
        args: |
           run - <script.js
      

#   k6_loadtest_local:
    
#     name: k6 local test run 
#     runs-on: ubuntu-latest
#     container: docker://loadimpact/k6:latest
# #     needs: [build]
  
#     steps:
#     - name: Checkout
#       uses: actions/checkout@v1
    
#     - name: Sleep
#       run: sleep 30
      
#     - name: Local k6 test
#       run: k6 run script.js
